#defines

GLODEF_SELECTION_RANDOM = 0
GLODEF_SELECTION_EGREEDY = 1
GLODEF_SELECTION_SOFTMAX = 2
GLODEF_SELECTION_UCB1 = 3
GLODEF_SELECTION_UCBTUNED = 4
GLODEF_SELECTION_POKER = 5
GLODEF_SELECTION_VOTER = 6

GLODEF_CHANGEPOINT_NONE = 0
GLODEF_CHANGEPOINT_PERIODICRESET = 1
GLODEF_CHANGEPOINT_Z_TEST = 2
GLODEF_CHANGEPOINT_HENKYPENKY = 3

GLODEF_CHANGEPOINT_TEST_Z1 = 0
GLODEF_CHANGEPOINT_TEST_Z2 = 1

GLODEF_RESET_ALGORITHM_RESET_ALL_TO_ZERO = 0
GLODEF_RESET_ALGORITHM_RESET_ALL_TO_MOVING_AVERAGE = 1
GLODEF_RESET_ALGORITHM_RESET_ALL_TO_MOVING_AVERAGE_CUTOFF = 2
GLODEF_RESET_ALGORITHM_RESET_TO_MOVING_AVERAGE = 3

GLODEF_OPTIMIZATION_ANNEALING = 0
GLODEF_OPTIMIZATION_GENETIC = 1
GLODEF_OPTIMIZATION_EXHAUSTIVE = 2
GLODEF_OPTIMIZATION_RANDOM = 3

GLODEF_FITNESS_SUMREWARDS = 0
GLODEF_FITNESS_REGRET = 1
GLODEF_FITNESS_OPTIMALITY = 2
GLODEF_FITNESS_OPTIMALITY_RANDNOR = 3

GLODEF_PARAM_FUNCTION_DIRECT = 0
GLODEF_PARAM_FUNCTION_LINEAR = 1
GLODEF_PARAM_FUNCTION_NEURAL = 2


def PrintStrings(L, newLine = True):
    if isinstance(str(L), basestring):
        if newLine:
            print str(L)
        else:
            print str(L),
    else:
        for x in L:
            PrintStrings(x, newLine)
